config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  #   resources :posts
  # end

  mount Sidekiq::Web => "/sidekiq"

  # Defines the root path route ("/")
  # resources :posts # RESTful enabling all
  resources :posts, only: [:index, :show]

  namespace :api do
    namespace :v1 do
      resources :posts, only: [:create]
      # get 'posts/create'
    end
  end
  
  root "posts#index"
end

app/models/api.rb
module Api
end

app/models/api/v1.rb
module Api
    module V1
    end
end

app/models/api/v1/post.rb
module Api
    module V1
        class Post
            include ActiveModel::Model
            include ContentEditable

            attr_accessor :title, :body, :writer_id,
                          :tags_string
        end
    end
end

# Api::V1::Post.new(title: "test", body: "cccc")

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/content_editable.rb
module ContentEditable
    extend ActiveSupport::Concern

    included do
      validate :body_more_than_10
      def body_more_than_10
        if body.nil? || body.length < 10
          errors.add(:body, "must have more than 10 characters")
        end
      end
    end

    class_methods do
    end
end

app/models/post.rb
class Post < ApplicationRecord
  include ContentEditable

  belongs_to :writer, counter_cache: true
  # post count is now cache with counter_cache
  # addressable by posts_count
  # custom posts_count -> couter_cache: :posts_count
  # migration is required
  # bundle exec rails g migration AddPostsCountToWriters posts_count:integer
  # bundle exec rails db:migrate
  # NAME MATTERS!! rails tries to understand migration and create script for you!!
  # Writer.reset_counters(id, :posts_count) -> to reset counters for given id

  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :views, class_name: "PostView"

  # validates :body, presence: true

  # after_initialize :assign_default_titte

  # def assign_default_titte
  #   self.title = 'untitled'
  # end

  # before_save
  # before_create
  # before_update
  # after_save
  # after_create
  # after_update

  # before_save :prepend_title

  # def prepend_title
  #   self.title = "Saved: #{title}"
  # end

  # def initialize(params={})
  #   super()
  # end

  after_create_commit :broadcast_prepend_to_post

  def broadcast_prepend_to_post
    broadcast_prepend_to(
      "posts_list",
      partial: "posts/post_row",
      locals: {
        post: self
      },
      target: "posts_result"
    )
  end

  def writer_name
    writer.name
  end

  def tags_string
    tags.pluck(:name).join(", ")
  end

  def tags_string=(value)
    # value example = "game, movie"
    words = value.split(",").map{|s| s.strip.downcase}

    tags.delete_all

    words.uniq.each do |word|
      tag = Tag.find_or_create_by(name: word)

      tags << tag
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/post_view.rb
class PostView < ApplicationRecord
  belongs_to :post
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tags, dependent: :destroy
    has_many :posts, through: :post_tags  
    validates :name, uniqueness: true
end

app/models/writer.rb
class Writer < ApplicationRecord
    has_many :posts, dependent: :destroy
    validates :name, uniqueness: true

    # def self.select_lists
    #     ...
    # end

    class << self
        def select_lists
            all.map{|writer| [writer.name, writer.id]}
        end
    end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def create
    post_params = params[:post].as_json
    # posts: { title:, body: }

    post = Api::V1::Post.new(post_params)

    if post.valid?
      render json: {}, status: 200
    else
      render json: {}, status: 422
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :skip_cookies, if: :not_signed_in?
    # before_action :sleep3
    before_action :set_locale

    def skip_cookies
        request.session_options[:skip] = true
    end

    def not_signed_in?
        session[:current_user_id].nil?
    end

    def sleep3
        sleep 3
    end

    def set_locale
        # I18n.locale = :th
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_meta, only: %i[ show ]

  NUMBER_PER_PAGE = 5

  # GET /posts or /posts.json
  def index
    @posts = Post.eager_load(:writer, :tags)
      .where("title LIKE '%#{params[:q]}%'")
      .order(created_at: :desc)
      .page(params[:page])
      .per(NUMBER_PER_PAGE)
  end

  # GET /posts/1 or /posts/1.json
  def show
    # PostView.create(post_id: @post.id)
    # change to job trigger

    CreatePostViewsJob.perform_later(post_id: @post.id)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.turbo_stream
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        # binding.irb
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.turbo_stream
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])

      # if stale?(@post)
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
      # render file: "#{Rails.root}/public/404.html", status: :not_found
    end

    def set_meta
      @meta = {
        title: @post.title
      }
    end

    # Only allow a list of trusted parameters through.
    def post_params
      # Strong parameters
      params.require(:post).permit(:title, :body, :writer_id, :tags_string)
    end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :meta %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/partials/_meta.html.erb
<meta name="twitter:title" content="<%= meta[:title] %>">

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :writer_id, style: "display: block" %>
    <%= form.select :writer_id, Writer.select_lists %>
    <!-- <%= form.text_field :writer_id %> -->
  </div>

  <div>
  <%= form.label :tags_string, style: "display: block" %>
  <%= form.text_field :tags_string %>
</div>

  <div>
    <%= form.submit %>
    <%= link_to 'Back', posts_path %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <h3><%= post.title %></h3>
  <p class="timestamp">created: <%= time_ago_in_words(post.created_at)%></p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

  <p>
    <strong>Tags:</strong>
    <%= post.tags_string %>
  </p>

  <p>
    <strong>Writer:</strong>
    <%= post.writer_name %>
  </p>

</div>

app/views/posts/_post_row.html.erb
<tr>
    <td>
        <%= link_to post.title, post %>
    </td>
    <td>
        <%= post.body %>
    </td>
    <td>
        <%= post.created_at %>
    </td>
    <td>
        <%= link_to "Edit", edit_post_path(post), class: "button", data: { turbo_frame: "edit_post_#{post.id}"} %>
        <%= button_to "Destroy", post, method: :delete, data: {turbo_confirm: "You sure?"} %>
    </td>
</tr>

app/views/posts/_post_row.turbo_stream.erb
<tr>
    <td>
        <%= link_to post.title, post %>
    </td>
    <td>
        <%= post.body %>
    </td>
    <td>
        <%= post.created_at %>
    </td>
    <td>
        <%= button_to "Destroy this post", post, method: :delete %>
    </td>
</tr>

app/views/posts/create.turbo_stream.erb
<turbo-stream action="replace" target="new_post">
    <template>
        <%= turbo_frame_tag 'new_post' do %>
        <% end %>
    </template>
</turbo-stream>

<turbo-stream action="replace" target="post-notice">
    <template>
        <div id="post-notice"></div>
        <p class="notice" data-controller="post-notice">
            Post <%= @post.id %> is successfully created.
            <a data-action="click->post-notice#close">close</a>
        </p>
    </template>
</turbo-stream>

<turbo-stream action="prepend" target="posts_result">
    <template>
        <%= render "posts/post_row", post: @post %>
    </template>
</turbo-stream>

app/views/posts/destroy.turbo_stream.erb
<turbo-stream action="replace" target="edit_post_<%= @post.id%>">
    <template>
    </template>
</turbo-stream>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= turbo_frame_tag "edit_post_#{@post.id}" do%>
  <%= render "form", post: @post %>
<% end %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.csv.erb
id,title,body
<% @posts.each do |post| %>
<%= "#{post.id},#{post.title},#{post.body}" %>
<% end %>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<%= link_to "New post", new_post_path, class: "button", data: {turbo_frame: "new_post"} %>

<%= turbo_frame_tag 'new_post' do %>
<% end %>

<div id="post-notice"></div>

<%= paginate @posts, views_prefix: :posts %>

<%= form_with url: "/posts", method: :get do |form| %>
  <%= form.text_field :q, value: params[:q] %>
  <%= form.submit "Search" %>
<% end %>

<%= turbo_stream_from "posts_list" %>

<div id="posts">
  <table>
    <thead>
      <tr>
        <th>title</th>
        <th>body</th>
        <th>created_at</th>
        <th>actions</th>
      </tr>
    </thead>
    <tbody id="posts_result">
    <% Rails.cache.fetch("posts_list_#{@posts.first}, expires_in: 10.minutes") do %>
      <% @posts.each do |post| %>
        <%= turbo_frame_tag "edit_post_#{post.id}" do %>
          <%= render "posts/post_row", post: post %>
        <% end %>
      <% end %>

      <%# cache post do %>
        <%#= turbo_frame_tag "edit_post_#{post.id}" do %>
          <%#= render "posts/post_row", post: post %>
        <%# end %>
      <%# end %>

    <% end %>

    <%# render partial: "posts/post_row", collection: @posts, cache:true %>
    </tbody>
  </table>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= turbo_frame_tag 'new_post' do %>
  <%= render "form", post: @post %>
<% end %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<% content_for :title do %>
  <%= "#{@post.title} - Geeky" %>
<% end %>

<% content_for :meta do %>
  <%= render "layouts/partials/meta", meta: @meta %>
<% end %>

<%= I18n.t "post.title" %>

<p style="color: green"><%= notice %></p>

<%# Fragment caching %>
<% cache @post do %>
  <%= render @post %>
<% end %>

 <%# cache_if admin?, @post do %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/posts/update.turbo_stream.erb
<turbo-stream action="replace" target="edit_post_<%= @post.id%>">
    <template>
    <%= turbo_frame_tag "edit_post_#{@post.id}" do %>
      <%= render "posts/post_row", post: @post %>
    <% end %>
    </template>
</turbo-stream>